on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Porter App Name'
        required: true
        default: 'jul18'
        type: string
      cluster:
        description: 'Porter Cluster ID'
        required: true
        default: '1'
        type: string
      deployment_target_id:
        description: 'Porter Deployment Target ID'
        required: true
        default: 'f79f9636-8b9c-4cc3-a068-5107fe55edfc'
        type: string
      host:
        description: 'Porter Host URL'
        required: true
        default: 'https://dgtown2.withporter.run'
        type: string
      project:
        description: 'Porter Project ID'
        required: true
        default: '1'
        type: string
      pr_number:
        description: 'PR Number (optional)'
        required: false
        type: string
      repo_name_override:
        description: 'Repository Name Override (optional - defaults to current repo)'
        required: false
        type: string
      tag_override:
        description: 'Tag Override (optional - defaults to short SHA)'
        required: false
        type: string
      docker_buildkit:
        description: 'Enable Docker BuildKit'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '0'
name: dgtown test
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
        
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply
        env:
          PORTER_APP_NAME: ${{ inputs.app_name }}
          PORTER_CLUSTER: ${{ inputs.cluster }}
          PORTER_DEPLOYMENT_TARGET_ID: ${{ inputs.deployment_target_id }}
          PORTER_HOST: ${{ inputs.host }}
          PORTER_PR_NUMBER: ${{ inputs.pr_number }}
          PORTER_PROJECT: ${{ inputs.project }}
          PORTER_REPO_NAME: ${{ inputs.repo_name_override || github.event.repository.name }}
          PORTER_TAG: ${{ inputs.tag_override || steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
          DOCKER_BUILDKIT: ${{ inputs.docker_buildkit }}
