"on":
  push:
    branches:
    - master
name: Deploy to test-switch
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f ./porter-dev.yaml
      env:
        PORTER_CLUSTER: "2956"
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_PROJECT: "8162"
        PORTER_STACK_NAME: test-switch
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_8162_2956 }}
