"on":
  push:
    branches:
      - master
name: Deploy to bbb
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply -f bbb.yaml
        env:
          PORTER_APP_NAME: bbb
          PORTER_CLUSTER: "2"
          PORTER_DEPLOYMENT_TARGET_ID: 434d6fa6-99e7-43eb-a707-81db78df244b
          PORTER_HOST: https://1e07-204-48-36-234.ngrok-free.app
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "1"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_1_2 }}
