"on":
    push:
        branches:
            - master
name: Deploy to build-feb24
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/dev-setup-porter@v0.0.1
              with:
                private_branch: dgtown/build-notifications
                token: ${{ secrets.PORTER_DEV_CODE_TOKEN}}
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: build-feb24
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 904c4a4c-c909-4c88-9d63-ca247687fe02
                PORTER_HOST: https://dgtown2.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
